//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.27 at 07:01:48 PM GST 
//


package generated;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SYMFTFUNDSHELDIN_QNAME = new QName("", "SYM_FT_FUNDS_HELD_IN");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SYMFTFUNDSHELDINType }
     * 
     */
    public SYMFTFUNDSHELDINType createSYMFTFUNDSHELDINType() {
        return new SYMFTFUNDSHELDINType();
    }

    /**
     * Create an instance of {@link SAHEADERINType }
     * 
     */
    public SAHEADERINType createSAHEADERINType() {
        return new SAHEADERINType();
    }

    /**
     * Create an instance of {@link FTFHCREDITACCTCOLLType }
     * 
     */
    public FTFHCREDITACCTCOLLType createFTFHCREDITACCTCOLLType() {
        return new FTFHCREDITACCTCOLLType();
    }

    /**
     * Create an instance of {@link FTPAYMENTCHANNELDATATType }
     * 
     */
    public FTPAYMENTCHANNELDATATType createFTPAYMENTCHANNELDATATType() {
        return new FTPAYMENTCHANNELDATATType();
    }

    /**
     * Create an instance of {@link FTPAYMENTCHANNELDATACOLLType }
     * 
     */
    public FTPAYMENTCHANNELDATACOLLType createFTPAYMENTCHANNELDATACOLLType() {
        return new FTPAYMENTCHANNELDATACOLLType();
    }

    /**
     * Create an instance of {@link FTFHCREDITACCTTType }
     * 
     */
    public FTFHCREDITACCTTType createFTFHCREDITACCTTType() {
        return new FTFHCREDITACCTTType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SYMFTFUNDSHELDINType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SYM_FT_FUNDS_HELD_IN")
    public JAXBElement<SYMFTFUNDSHELDINType> createSYMFTFUNDSHELDIN(SYMFTFUNDSHELDINType value) {
        return new JAXBElement<SYMFTFUNDSHELDINType>(_SYMFTFUNDSHELDIN_QNAME, SYMFTFUNDSHELDINType.class, null, value);
    }

}
