//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.27 at 07:01:48 PM GST 
//


package generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SYM_FT_FUNDS_HELD_INType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SYM_FT_FUNDS_HELD_INType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HEADER_IN" type="{}SA_HEADER_INType"/>
 *         &lt;element name="HOST_CHECK_FLAG">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FT_TRAN_TYPE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ACCT_NO">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="START_DATE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="19"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="END_DATE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="19"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RESTRAINT_TYPE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PLEDGED_AMT" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="CCY">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NARRATIVE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="240"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FORCE_FUNDS_HELD">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="REFERENCE_NO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="13"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SOURCE_MODULE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LAST_CHANGE_OFFICER" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FH_OPERATION">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FH_SEQ_NO" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="FT_FH_CREDIT_ACCT_IN" type="{}FT_FH_CREDIT_ACCT_COLLType" minOccurs="0"/>
 *         &lt;element name="FT_PAYMENT_CHANNEL_DATA_IN" type="{}FT_PAYMENT_CHANNEL_DATA_COLLType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SYM_FT_FUNDS_HELD_INType", propOrder = {
    "headerin",
    "hostcheckflag",
    "fttrantype",
    "acctno",
    "startdate",
    "enddate",
    "restrainttype",
    "pledgedamt",
    "ccy",
    "narrative",
    "forcefundsheld",
    "referenceno",
    "sourcemodule",
    "lastchangeofficer",
    "fhoperation",
    "fhseqno",
    "ftfhcreditacctin",
    "ftpaymentchanneldatain"
})
public class SYMFTFUNDSHELDINType {

    @XmlElement(name = "HEADER_IN", required = true)
    protected SAHEADERINType headerin;
    @XmlElement(name = "HOST_CHECK_FLAG", required = true)
    protected String hostcheckflag;
    @XmlElement(name = "FT_TRAN_TYPE", required = true)
    protected String fttrantype;
    @XmlElement(name = "ACCT_NO", required = true)
    protected String acctno;
    @XmlElement(name = "START_DATE", required = true)
    protected String startdate;
    @XmlElement(name = "END_DATE", required = true)
    protected String enddate;
    @XmlElement(name = "RESTRAINT_TYPE", required = true)
    protected String restrainttype;
    @XmlElement(name = "PLEDGED_AMT")
    protected double pledgedamt;
    @XmlElement(name = "CCY", required = true)
    protected String ccy;
    @XmlElement(name = "NARRATIVE")
    protected String narrative;
    @XmlElement(name = "FORCE_FUNDS_HELD", required = true)
    protected String forcefundsheld;
    @XmlElement(name = "REFERENCE_NO")
    protected String referenceno;
    @XmlElement(name = "SOURCE_MODULE", required = true)
    protected String sourcemodule;
    @XmlElement(name = "LAST_CHANGE_OFFICER")
    protected String lastchangeofficer;
    @XmlElement(name = "FH_OPERATION", required = true)
    protected String fhoperation;
    @XmlElement(name = "FH_SEQ_NO")
    protected Double fhseqno;
    @XmlElement(name = "FT_FH_CREDIT_ACCT_IN")
    protected FTFHCREDITACCTCOLLType ftfhcreditacctin;
    @XmlElement(name = "FT_PAYMENT_CHANNEL_DATA_IN")
    protected FTPAYMENTCHANNELDATACOLLType ftpaymentchanneldatain;

    /**
     * Gets the value of the headerin property.
     * 
     * @return
     *     possible object is
     *     {@link SAHEADERINType }
     *     
     */
    public SAHEADERINType getHEADERIN() {
        return headerin;
    }

    /**
     * Sets the value of the headerin property.
     * 
     * @param value
     *     allowed object is
     *     {@link SAHEADERINType }
     *     
     */
    public void setHEADERIN(SAHEADERINType value) {
        this.headerin = value;
    }

    /**
     * Gets the value of the hostcheckflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHOSTCHECKFLAG() {
        return hostcheckflag;
    }

    /**
     * Sets the value of the hostcheckflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHOSTCHECKFLAG(String value) {
        this.hostcheckflag = value;
    }

    /**
     * Gets the value of the fttrantype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFTTRANTYPE() {
        return fttrantype;
    }

    /**
     * Sets the value of the fttrantype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFTTRANTYPE(String value) {
        this.fttrantype = value;
    }

    /**
     * Gets the value of the acctno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCTNO() {
        return acctno;
    }

    /**
     * Sets the value of the acctno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCTNO(String value) {
        this.acctno = value;
    }

    /**
     * Gets the value of the startdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTARTDATE() {
        return startdate;
    }

    /**
     * Sets the value of the startdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTARTDATE(String value) {
        this.startdate = value;
    }

    /**
     * Gets the value of the enddate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENDDATE() {
        return enddate;
    }

    /**
     * Sets the value of the enddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENDDATE(String value) {
        this.enddate = value;
    }

    /**
     * Gets the value of the restrainttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRESTRAINTTYPE() {
        return restrainttype;
    }

    /**
     * Sets the value of the restrainttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRESTRAINTTYPE(String value) {
        this.restrainttype = value;
    }

    /**
     * Gets the value of the pledgedamt property.
     * 
     */
    public double getPLEDGEDAMT() {
        return pledgedamt;
    }

    /**
     * Sets the value of the pledgedamt property.
     * 
     */
    public void setPLEDGEDAMT(double value) {
        this.pledgedamt = value;
    }

    /**
     * Gets the value of the ccy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCY() {
        return ccy;
    }

    /**
     * Sets the value of the ccy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCY(String value) {
        this.ccy = value;
    }

    /**
     * Gets the value of the narrative property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNARRATIVE() {
        return narrative;
    }

    /**
     * Sets the value of the narrative property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNARRATIVE(String value) {
        this.narrative = value;
    }

    /**
     * Gets the value of the forcefundsheld property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFORCEFUNDSHELD() {
        return forcefundsheld;
    }

    /**
     * Sets the value of the forcefundsheld property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFORCEFUNDSHELD(String value) {
        this.forcefundsheld = value;
    }

    /**
     * Gets the value of the referenceno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREFERENCENO() {
        return referenceno;
    }

    /**
     * Sets the value of the referenceno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREFERENCENO(String value) {
        this.referenceno = value;
    }

    /**
     * Gets the value of the sourcemodule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOURCEMODULE() {
        return sourcemodule;
    }

    /**
     * Sets the value of the sourcemodule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOURCEMODULE(String value) {
        this.sourcemodule = value;
    }

    /**
     * Gets the value of the lastchangeofficer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLASTCHANGEOFFICER() {
        return lastchangeofficer;
    }

    /**
     * Sets the value of the lastchangeofficer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLASTCHANGEOFFICER(String value) {
        this.lastchangeofficer = value;
    }

    /**
     * Gets the value of the fhoperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFHOPERATION() {
        return fhoperation;
    }

    /**
     * Sets the value of the fhoperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFHOPERATION(String value) {
        this.fhoperation = value;
    }

    /**
     * Gets the value of the fhseqno property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFHSEQNO() {
        return fhseqno;
    }

    /**
     * Sets the value of the fhseqno property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFHSEQNO(Double value) {
        this.fhseqno = value;
    }

    /**
     * Gets the value of the ftfhcreditacctin property.
     * 
     * @return
     *     possible object is
     *     {@link FTFHCREDITACCTCOLLType }
     *     
     */
    public FTFHCREDITACCTCOLLType getFTFHCREDITACCTIN() {
        return ftfhcreditacctin;
    }

    /**
     * Sets the value of the ftfhcreditacctin property.
     * 
     * @param value
     *     allowed object is
     *     {@link FTFHCREDITACCTCOLLType }
     *     
     */
    public void setFTFHCREDITACCTIN(FTFHCREDITACCTCOLLType value) {
        this.ftfhcreditacctin = value;
    }

    /**
     * Gets the value of the ftpaymentchanneldatain property.
     * 
     * @return
     *     possible object is
     *     {@link FTPAYMENTCHANNELDATACOLLType }
     *     
     */
    public FTPAYMENTCHANNELDATACOLLType getFTPAYMENTCHANNELDATAIN() {
        return ftpaymentchanneldatain;
    }

    /**
     * Sets the value of the ftpaymentchanneldatain property.
     * 
     * @param value
     *     allowed object is
     *     {@link FTPAYMENTCHANNELDATACOLLType }
     *     
     */
    public void setFTPAYMENTCHANNELDATAIN(FTPAYMENTCHANNELDATACOLLType value) {
        this.ftpaymentchanneldatain = value;
    }

}
