//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.21 at 04:05:40 AM GST 
//


package generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FT_CHARGES_CC_TType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FT_CHARGES_CC_TType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="POSITION" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="CHARGE_TYPE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OUR_BEN_IND">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TRAN_CCY">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TRAN_CCY_AMT" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="CALC_CCY" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BASE_FOR_CALC" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="EXCH_RATE" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="QUOTE_TYPE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CHARGE_CCY">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CHARGE_CCY_AMT" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="BASE_EQUIV" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="CHANGED_FLAG" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TAX_AMT" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FT_CHARGES_CC_TType", propOrder = {
    "position",
    "chargetype",
    "ourbenind",
    "tranccy",
    "tranccyamt",
    "calcccy",
    "baseforcalc",
    "exchrate",
    "quotetype",
    "chargeccy",
    "chargeccyamt",
    "baseequiv",
    "changedflag",
    "taxamt"
})
public class FTCHARGESCCTType {

    @XmlElement(name = "POSITION")
    protected double position;
    @XmlElement(name = "CHARGE_TYPE", required = true)
    protected String chargetype;
    @XmlElement(name = "OUR_BEN_IND", required = true)
    protected String ourbenind;
    @XmlElement(name = "TRAN_CCY", required = true)
    protected String tranccy;
    @XmlElement(name = "TRAN_CCY_AMT")
    protected double tranccyamt;
    @XmlElement(name = "CALC_CCY")
    protected String calcccy;
    @XmlElement(name = "BASE_FOR_CALC")
    protected Double baseforcalc;
    @XmlElement(name = "EXCH_RATE")
    protected Double exchrate;
    @XmlElement(name = "QUOTE_TYPE")
    protected String quotetype;
    @XmlElement(name = "CHARGE_CCY", required = true)
    protected String chargeccy;
    @XmlElement(name = "CHARGE_CCY_AMT")
    protected double chargeccyamt;
    @XmlElement(name = "BASE_EQUIV")
    protected Double baseequiv;
    @XmlElement(name = "CHANGED_FLAG")
    protected String changedflag;
    @XmlElement(name = "TAX_AMT")
    protected Double taxamt;

    /**
     * Gets the value of the position property.
     * 
     */
    public double getPOSITION() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     */
    public void setPOSITION(double value) {
        this.position = value;
    }

    /**
     * Gets the value of the chargetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHARGETYPE() {
        return chargetype;
    }

    /**
     * Sets the value of the chargetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHARGETYPE(String value) {
        this.chargetype = value;
    }

    /**
     * Gets the value of the ourbenind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOURBENIND() {
        return ourbenind;
    }

    /**
     * Sets the value of the ourbenind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOURBENIND(String value) {
        this.ourbenind = value;
    }

    /**
     * Gets the value of the tranccy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANCCY() {
        return tranccy;
    }

    /**
     * Sets the value of the tranccy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANCCY(String value) {
        this.tranccy = value;
    }

    /**
     * Gets the value of the tranccyamt property.
     * 
     */
    public double getTRANCCYAMT() {
        return tranccyamt;
    }

    /**
     * Sets the value of the tranccyamt property.
     * 
     */
    public void setTRANCCYAMT(double value) {
        this.tranccyamt = value;
    }

    /**
     * Gets the value of the calcccy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCALCCCY() {
        return calcccy;
    }

    /**
     * Sets the value of the calcccy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCALCCCY(String value) {
        this.calcccy = value;
    }

    /**
     * Gets the value of the baseforcalc property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBASEFORCALC() {
        return baseforcalc;
    }

    /**
     * Sets the value of the baseforcalc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBASEFORCALC(Double value) {
        this.baseforcalc = value;
    }

    /**
     * Gets the value of the exchrate property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getEXCHRATE() {
        return exchrate;
    }

    /**
     * Sets the value of the exchrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setEXCHRATE(Double value) {
        this.exchrate = value;
    }

    /**
     * Gets the value of the quotetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQUOTETYPE() {
        return quotetype;
    }

    /**
     * Sets the value of the quotetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQUOTETYPE(String value) {
        this.quotetype = value;
    }

    /**
     * Gets the value of the chargeccy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHARGECCY() {
        return chargeccy;
    }

    /**
     * Sets the value of the chargeccy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHARGECCY(String value) {
        this.chargeccy = value;
    }

    /**
     * Gets the value of the chargeccyamt property.
     * 
     */
    public double getCHARGECCYAMT() {
        return chargeccyamt;
    }

    /**
     * Sets the value of the chargeccyamt property.
     * 
     */
    public void setCHARGECCYAMT(double value) {
        this.chargeccyamt = value;
    }

    /**
     * Gets the value of the baseequiv property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBASEEQUIV() {
        return baseequiv;
    }

    /**
     * Sets the value of the baseequiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBASEEQUIV(Double value) {
        this.baseequiv = value;
    }

    /**
     * Gets the value of the changedflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHANGEDFLAG() {
        return changedflag;
    }

    /**
     * Sets the value of the changedflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHANGEDFLAG(String value) {
        this.changedflag = value;
    }

    /**
     * Gets the value of the taxamt property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTAXAMT() {
        return taxamt;
    }

    /**
     * Sets the value of the taxamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTAXAMT(Double value) {
        this.taxamt = value;
    }

}
