//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.21 at 04:05:40 AM GST 
//


package generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SYM_FT_TRANSFER_CC_INType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SYM_FT_TRANSFER_CC_INType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HEADER_IN" type="{}SA_HEADER_INType"/>
 *         &lt;element name="HOST_CHECK_FLAG" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PROCESS_INDICATOR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TRAN_DATE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="19"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TRAN_TYPE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BOOK_BRANCH" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TRAN_COUNTRY" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PMT_TITLE" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="FIXED_SIDE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DR_VALUE_DATE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="19"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DR_CCY" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DR_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="DR_CLIENT_NO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DR_ACCT_NO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DR_GL_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="16"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DR_BRANCH" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DR_SEQ_NO" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="DR_PROFIT_CENTRE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DR_SETTLE_MTD" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DR_CHARGE_ACCT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CR_VALUE_DATE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="19"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CR_CCY" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CR_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="CR_CLIENT_NO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CR_ACCT_NO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CR_GL_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="16"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CR_BRANCH" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CR_SEQ_NO" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="CR_PROFIT_CENTRE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CR_SETTLE_MTD" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CR_CHARGE_ACCT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SPOT_RATE" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="NARRATIVE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="143"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BEN_ACCT_NO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="34"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BEN_NAME_ADDRESS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="143"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BEN_BNK_ID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="11"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BENBNK_NAME_ADDRESS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="143"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ORD_CLIENT_ACCT_NO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="34"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ORD_CLIENT_NAME_ADDRESS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="143"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ORD_CLIENT_BNK_ID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="11"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ORD_CLIENT_SWIFT_OPT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DETAILS_OF_PMT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="143"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DETAILS_OF_CHRG" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SENDER_TO_RECEIVER_INFO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="215"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FH_REF_NO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CR_NARRATIVE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="105"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DR_NARRATIVE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="105"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CHANNEL_REF_NO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FT_PAYMENT_CHANNEL_DATA_IN" type="{}FT_PAYMENT_CHANNEL_DATA_COLLType" minOccurs="0"/>
 *         &lt;element name="FT_CHARGES_CC_IN" type="{}FT_CHARGES_CC_COLLType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SYM_FT_TRANSFER_CC_INType", propOrder = {
    "headerin",
    "hostcheckflag",
    "processindicator",
    "trandate",
    "trantype",
    "bookbranch",
    "trancountry",
    "pmttitle",
    "fixedside",
    "drvaluedate",
    "drccy",
    "dramount",
    "drclientno",
    "dracctno",
    "drglcode",
    "drbranch",
    "drseqno",
    "drprofitcentre",
    "drsettlemtd",
    "drchargeacct",
    "crvaluedate",
    "crccy",
    "cramount",
    "crclientno",
    "cracctno",
    "crglcode",
    "crbranch",
    "crseqno",
    "crprofitcentre",
    "crsettlemtd",
    "crchargeacct",
    "spotrate",
    "narrative",
    "benacctno",
    "bennameaddress",
    "benbnkid",
    "benbnknameaddress",
    "ordclientacctno",
    "ordclientnameaddress",
    "ordclientbnkid",
    "ordclientswiftopt",
    "detailsofpmt",
    "detailsofchrg",
    "sendertoreceiverinfo",
    "fhrefno",
    "crnarrative",
    "drnarrative",
    "channelrefno",
    "ftpaymentchanneldatain",
    "ftchargesccin"
})
public class SYMFTTRANSFERCCINType {

    @XmlElement(name = "HEADER_IN", required = true)
    protected SAHEADERINType headerin;
    @XmlElement(name = "HOST_CHECK_FLAG")
    protected String hostcheckflag;
    @XmlElement(name = "PROCESS_INDICATOR")
    protected String processindicator;
    @XmlElement(name = "TRAN_DATE")
    protected String trandate;
    @XmlElement(name = "TRAN_TYPE")
    protected String trantype;
    @XmlElement(name = "BOOK_BRANCH")
    protected String bookbranch;
    @XmlElement(name = "TRAN_COUNTRY")
    protected String trancountry;
    @XmlElement(name = "PMT_TITLE")
    protected Double pmttitle;
    @XmlElement(name = "FIXED_SIDE")
    protected String fixedside;
    @XmlElement(name = "DR_VALUE_DATE")
    protected String drvaluedate;
    @XmlElement(name = "DR_CCY")
    protected String drccy;
    @XmlElement(name = "DR_AMOUNT")
    protected Double dramount;
    @XmlElement(name = "DR_CLIENT_NO")
    protected String drclientno;
    @XmlElement(name = "DR_ACCT_NO")
    protected String dracctno;
    @XmlElement(name = "DR_GL_CODE")
    protected String drglcode;
    @XmlElement(name = "DR_BRANCH")
    protected String drbranch;
    @XmlElement(name = "DR_SEQ_NO")
    protected Double drseqno;
    @XmlElement(name = "DR_PROFIT_CENTRE")
    protected String drprofitcentre;
    @XmlElement(name = "DR_SETTLE_MTD")
    protected String drsettlemtd;
    @XmlElement(name = "DR_CHARGE_ACCT")
    protected String drchargeacct;
    @XmlElement(name = "CR_VALUE_DATE")
    protected String crvaluedate;
    @XmlElement(name = "CR_CCY")
    protected String crccy;
    @XmlElement(name = "CR_AMOUNT")
    protected Double cramount;
    @XmlElement(name = "CR_CLIENT_NO")
    protected String crclientno;
    @XmlElement(name = "CR_ACCT_NO")
    protected String cracctno;
    @XmlElement(name = "CR_GL_CODE")
    protected String crglcode;
    @XmlElement(name = "CR_BRANCH")
    protected String crbranch;
    @XmlElement(name = "CR_SEQ_NO")
    protected Double crseqno;
    @XmlElement(name = "CR_PROFIT_CENTRE")
    protected String crprofitcentre;
    @XmlElement(name = "CR_SETTLE_MTD")
    protected String crsettlemtd;
    @XmlElement(name = "CR_CHARGE_ACCT")
    protected String crchargeacct;
    @XmlElement(name = "SPOT_RATE")
    protected Double spotrate;
    @XmlElement(name = "NARRATIVE")
    protected String narrative;
    @XmlElement(name = "BEN_ACCT_NO")
    protected String benacctno;
    @XmlElement(name = "BEN_NAME_ADDRESS")
    protected String bennameaddress;
    @XmlElement(name = "BEN_BNK_ID")
    protected String benbnkid;
    @XmlElement(name = "BENBNK_NAME_ADDRESS")
    protected String benbnknameaddress;
    @XmlElement(name = "ORD_CLIENT_ACCT_NO")
    protected String ordclientacctno;
    @XmlElement(name = "ORD_CLIENT_NAME_ADDRESS")
    protected String ordclientnameaddress;
    @XmlElement(name = "ORD_CLIENT_BNK_ID")
    protected String ordclientbnkid;
    @XmlElement(name = "ORD_CLIENT_SWIFT_OPT")
    protected String ordclientswiftopt;
    @XmlElement(name = "DETAILS_OF_PMT")
    protected String detailsofpmt;
    @XmlElement(name = "DETAILS_OF_CHRG")
    protected String detailsofchrg;
    @XmlElement(name = "SENDER_TO_RECEIVER_INFO")
    protected String sendertoreceiverinfo;
    @XmlElement(name = "FH_REF_NO")
    protected String fhrefno;
    @XmlElement(name = "CR_NARRATIVE")
    protected String crnarrative;
    @XmlElement(name = "DR_NARRATIVE")
    protected String drnarrative;
    @XmlElement(name = "CHANNEL_REF_NO")
    protected String channelrefno;
    @XmlElement(name = "FT_PAYMENT_CHANNEL_DATA_IN")
    protected FTPAYMENTCHANNELDATACOLLType ftpaymentchanneldatain;
    @XmlElement(name = "FT_CHARGES_CC_IN")
    protected FTCHARGESCCCOLLType ftchargesccin;

    /**
     * Gets the value of the headerin property.
     * 
     * @return
     *     possible object is
     *     {@link SAHEADERINType }
     *     
     */
    public SAHEADERINType getHEADERIN() {
        return headerin;
    }

    /**
     * Sets the value of the headerin property.
     * 
     * @param value
     *     allowed object is
     *     {@link SAHEADERINType }
     *     
     */
    public void setHEADERIN(SAHEADERINType value) {
        this.headerin = value;
    }

    /**
     * Gets the value of the hostcheckflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHOSTCHECKFLAG() {
        return hostcheckflag;
    }

    /**
     * Sets the value of the hostcheckflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHOSTCHECKFLAG(String value) {
        this.hostcheckflag = value;
    }

    /**
     * Gets the value of the processindicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPROCESSINDICATOR() {
        return processindicator;
    }

    /**
     * Sets the value of the processindicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPROCESSINDICATOR(String value) {
        this.processindicator = value;
    }

    /**
     * Gets the value of the trandate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANDATE() {
        return trandate;
    }

    /**
     * Sets the value of the trandate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANDATE(String value) {
        this.trandate = value;
    }

    /**
     * Gets the value of the trantype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANTYPE() {
        return trantype;
    }

    /**
     * Sets the value of the trantype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANTYPE(String value) {
        this.trantype = value;
    }

    /**
     * Gets the value of the bookbranch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBOOKBRANCH() {
        return bookbranch;
    }

    /**
     * Sets the value of the bookbranch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBOOKBRANCH(String value) {
        this.bookbranch = value;
    }

    /**
     * Gets the value of the trancountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANCOUNTRY() {
        return trancountry;
    }

    /**
     * Sets the value of the trancountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANCOUNTRY(String value) {
        this.trancountry = value;
    }

    /**
     * Gets the value of the pmttitle property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPMTTITLE() {
        return pmttitle;
    }

    /**
     * Sets the value of the pmttitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPMTTITLE(Double value) {
        this.pmttitle = value;
    }

    /**
     * Gets the value of the fixedside property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIXEDSIDE() {
        return fixedside;
    }

    /**
     * Sets the value of the fixedside property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIXEDSIDE(String value) {
        this.fixedside = value;
    }

    /**
     * Gets the value of the drvaluedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRVALUEDATE() {
        return drvaluedate;
    }

    /**
     * Sets the value of the drvaluedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRVALUEDATE(String value) {
        this.drvaluedate = value;
    }

    /**
     * Gets the value of the drccy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRCCY() {
        return drccy;
    }

    /**
     * Sets the value of the drccy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRCCY(String value) {
        this.drccy = value;
    }

    /**
     * Gets the value of the dramount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDRAMOUNT() {
        return dramount;
    }

    /**
     * Sets the value of the dramount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDRAMOUNT(Double value) {
        this.dramount = value;
    }

    /**
     * Gets the value of the drclientno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRCLIENTNO() {
        return drclientno;
    }

    /**
     * Sets the value of the drclientno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRCLIENTNO(String value) {
        this.drclientno = value;
    }

    /**
     * Gets the value of the dracctno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRACCTNO() {
        return dracctno;
    }

    /**
     * Sets the value of the dracctno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRACCTNO(String value) {
        this.dracctno = value;
    }

    /**
     * Gets the value of the drglcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRGLCODE() {
        return drglcode;
    }

    /**
     * Sets the value of the drglcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRGLCODE(String value) {
        this.drglcode = value;
    }

    /**
     * Gets the value of the drbranch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRBRANCH() {
        return drbranch;
    }

    /**
     * Sets the value of the drbranch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRBRANCH(String value) {
        this.drbranch = value;
    }

    /**
     * Gets the value of the drseqno property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDRSEQNO() {
        return drseqno;
    }

    /**
     * Sets the value of the drseqno property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDRSEQNO(Double value) {
        this.drseqno = value;
    }

    /**
     * Gets the value of the drprofitcentre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRPROFITCENTRE() {
        return drprofitcentre;
    }

    /**
     * Sets the value of the drprofitcentre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRPROFITCENTRE(String value) {
        this.drprofitcentre = value;
    }

    /**
     * Gets the value of the drsettlemtd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRSETTLEMTD() {
        return drsettlemtd;
    }

    /**
     * Sets the value of the drsettlemtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRSETTLEMTD(String value) {
        this.drsettlemtd = value;
    }

    /**
     * Gets the value of the drchargeacct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRCHARGEACCT() {
        return drchargeacct;
    }

    /**
     * Sets the value of the drchargeacct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRCHARGEACCT(String value) {
        this.drchargeacct = value;
    }

    /**
     * Gets the value of the crvaluedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRVALUEDATE() {
        return crvaluedate;
    }

    /**
     * Sets the value of the crvaluedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRVALUEDATE(String value) {
        this.crvaluedate = value;
    }

    /**
     * Gets the value of the crccy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRCCY() {
        return crccy;
    }

    /**
     * Sets the value of the crccy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRCCY(String value) {
        this.crccy = value;
    }

    /**
     * Gets the value of the cramount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCRAMOUNT() {
        return cramount;
    }

    /**
     * Sets the value of the cramount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCRAMOUNT(Double value) {
        this.cramount = value;
    }

    /**
     * Gets the value of the crclientno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRCLIENTNO() {
        return crclientno;
    }

    /**
     * Sets the value of the crclientno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRCLIENTNO(String value) {
        this.crclientno = value;
    }

    /**
     * Gets the value of the cracctno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRACCTNO() {
        return cracctno;
    }

    /**
     * Sets the value of the cracctno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRACCTNO(String value) {
        this.cracctno = value;
    }

    /**
     * Gets the value of the crglcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRGLCODE() {
        return crglcode;
    }

    /**
     * Sets the value of the crglcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRGLCODE(String value) {
        this.crglcode = value;
    }

    /**
     * Gets the value of the crbranch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRBRANCH() {
        return crbranch;
    }

    /**
     * Sets the value of the crbranch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRBRANCH(String value) {
        this.crbranch = value;
    }

    /**
     * Gets the value of the crseqno property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCRSEQNO() {
        return crseqno;
    }

    /**
     * Sets the value of the crseqno property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCRSEQNO(Double value) {
        this.crseqno = value;
    }

    /**
     * Gets the value of the crprofitcentre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRPROFITCENTRE() {
        return crprofitcentre;
    }

    /**
     * Sets the value of the crprofitcentre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRPROFITCENTRE(String value) {
        this.crprofitcentre = value;
    }

    /**
     * Gets the value of the crsettlemtd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRSETTLEMTD() {
        return crsettlemtd;
    }

    /**
     * Sets the value of the crsettlemtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRSETTLEMTD(String value) {
        this.crsettlemtd = value;
    }

    /**
     * Gets the value of the crchargeacct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRCHARGEACCT() {
        return crchargeacct;
    }

    /**
     * Sets the value of the crchargeacct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRCHARGEACCT(String value) {
        this.crchargeacct = value;
    }

    /**
     * Gets the value of the spotrate property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSPOTRATE() {
        return spotrate;
    }

    /**
     * Sets the value of the spotrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSPOTRATE(Double value) {
        this.spotrate = value;
    }

    /**
     * Gets the value of the narrative property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNARRATIVE() {
        return narrative;
    }

    /**
     * Sets the value of the narrative property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNARRATIVE(String value) {
        this.narrative = value;
    }

    /**
     * Gets the value of the benacctno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBENACCTNO() {
        return benacctno;
    }

    /**
     * Sets the value of the benacctno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBENACCTNO(String value) {
        this.benacctno = value;
    }

    /**
     * Gets the value of the bennameaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBENNAMEADDRESS() {
        return bennameaddress;
    }

    /**
     * Sets the value of the bennameaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBENNAMEADDRESS(String value) {
        this.bennameaddress = value;
    }

    /**
     * Gets the value of the benbnkid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBENBNKID() {
        return benbnkid;
    }

    /**
     * Sets the value of the benbnkid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBENBNKID(String value) {
        this.benbnkid = value;
    }

    /**
     * Gets the value of the benbnknameaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBENBNKNAMEADDRESS() {
        return benbnknameaddress;
    }

    /**
     * Sets the value of the benbnknameaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBENBNKNAMEADDRESS(String value) {
        this.benbnknameaddress = value;
    }

    /**
     * Gets the value of the ordclientacctno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDCLIENTACCTNO() {
        return ordclientacctno;
    }

    /**
     * Sets the value of the ordclientacctno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDCLIENTACCTNO(String value) {
        this.ordclientacctno = value;
    }

    /**
     * Gets the value of the ordclientnameaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDCLIENTNAMEADDRESS() {
        return ordclientnameaddress;
    }

    /**
     * Sets the value of the ordclientnameaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDCLIENTNAMEADDRESS(String value) {
        this.ordclientnameaddress = value;
    }

    /**
     * Gets the value of the ordclientbnkid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDCLIENTBNKID() {
        return ordclientbnkid;
    }

    /**
     * Sets the value of the ordclientbnkid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDCLIENTBNKID(String value) {
        this.ordclientbnkid = value;
    }

    /**
     * Gets the value of the ordclientswiftopt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDCLIENTSWIFTOPT() {
        return ordclientswiftopt;
    }

    /**
     * Sets the value of the ordclientswiftopt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDCLIENTSWIFTOPT(String value) {
        this.ordclientswiftopt = value;
    }

    /**
     * Gets the value of the detailsofpmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDETAILSOFPMT() {
        return detailsofpmt;
    }

    /**
     * Sets the value of the detailsofpmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDETAILSOFPMT(String value) {
        this.detailsofpmt = value;
    }

    /**
     * Gets the value of the detailsofchrg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDETAILSOFCHRG() {
        return detailsofchrg;
    }

    /**
     * Sets the value of the detailsofchrg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDETAILSOFCHRG(String value) {
        this.detailsofchrg = value;
    }

    /**
     * Gets the value of the sendertoreceiverinfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSENDERTORECEIVERINFO() {
        return sendertoreceiverinfo;
    }

    /**
     * Sets the value of the sendertoreceiverinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSENDERTORECEIVERINFO(String value) {
        this.sendertoreceiverinfo = value;
    }

    /**
     * Gets the value of the fhrefno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFHREFNO() {
        return fhrefno;
    }

    /**
     * Sets the value of the fhrefno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFHREFNO(String value) {
        this.fhrefno = value;
    }

    /**
     * Gets the value of the crnarrative property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRNARRATIVE() {
        return crnarrative;
    }

    /**
     * Sets the value of the crnarrative property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRNARRATIVE(String value) {
        this.crnarrative = value;
    }

    /**
     * Gets the value of the drnarrative property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRNARRATIVE() {
        return drnarrative;
    }

    /**
     * Sets the value of the drnarrative property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRNARRATIVE(String value) {
        this.drnarrative = value;
    }

    /**
     * Gets the value of the channelrefno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHANNELREFNO() {
        return channelrefno;
    }

    /**
     * Sets the value of the channelrefno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHANNELREFNO(String value) {
        this.channelrefno = value;
    }

    /**
     * Gets the value of the ftpaymentchanneldatain property.
     * 
     * @return
     *     possible object is
     *     {@link FTPAYMENTCHANNELDATACOLLType }
     *     
     */
    public FTPAYMENTCHANNELDATACOLLType getFTPAYMENTCHANNELDATAIN() {
        return ftpaymentchanneldatain;
    }

    /**
     * Sets the value of the ftpaymentchanneldatain property.
     * 
     * @param value
     *     allowed object is
     *     {@link FTPAYMENTCHANNELDATACOLLType }
     *     
     */
    public void setFTPAYMENTCHANNELDATAIN(FTPAYMENTCHANNELDATACOLLType value) {
        this.ftpaymentchanneldatain = value;
    }

    /**
     * Gets the value of the ftchargesccin property.
     * 
     * @return
     *     possible object is
     *     {@link FTCHARGESCCCOLLType }
     *     
     */
    public FTCHARGESCCCOLLType getFTCHARGESCCIN() {
        return ftchargesccin;
    }

    /**
     * Sets the value of the ftchargesccin property.
     * 
     * @param value
     *     allowed object is
     *     {@link FTCHARGESCCCOLLType }
     *     
     */
    public void setFTCHARGESCCIN(FTCHARGESCCCOLLType value) {
        this.ftchargesccin = value;
    }

}
