//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.21 at 04:06:32 AM GST 
//


package generated;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SYMSTDOUT_QNAME = new QName("", "SYM_STD_OUT");
    private final static QName _SYMFTTRANSFERCCOUT_QNAME = new QName("", "SYM_FT_TRANSFER_CC_OUT");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SYMSTDOUTType }
     * 
     */
    public SYMSTDOUTType createSYMSTDOUTType() {
        return new SYMSTDOUTType();
    }

    /**
     * Create an instance of {@link SYMFTTRANSFERCCOUTType }
     * 
     */
    public SYMFTTRANSFERCCOUTType createSYMFTTRANSFERCCOUTType() {
        return new SYMFTTRANSFERCCOUTType();
    }

    /**
     * Create an instance of {@link SAERRLISTType }
     * 
     */
    public SAERRLISTType createSAERRLISTType() {
        return new SAERRLISTType();
    }

    /**
     * Create an instance of {@link SAERRType }
     * 
     */
    public SAERRType createSAERRType() {
        return new SAERRType();
    }

    /**
     * Create an instance of {@link SAERRORSType }
     * 
     */
    public SAERRORSType createSAERRORSType() {
        return new SAERRORSType();
    }

    /**
     * Create an instance of {@link SABUGType }
     * 
     */
    public SABUGType createSABUGType() {
        return new SABUGType();
    }

    /**
     * Create an instance of {@link SAHEADEROUTType }
     * 
     */
    public SAHEADEROUTType createSAHEADEROUTType() {
        return new SAHEADEROUTType();
    }

    /**
     * Create an instance of {@link SABUGLISTType }
     * 
     */
    public SABUGLISTType createSABUGLISTType() {
        return new SABUGLISTType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SYMSTDOUTType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SYM_STD_OUT")
    public JAXBElement<SYMSTDOUTType> createSYMSTDOUT(SYMSTDOUTType value) {
        return new JAXBElement<SYMSTDOUTType>(_SYMSTDOUT_QNAME, SYMSTDOUTType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SYMFTTRANSFERCCOUTType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SYM_FT_TRANSFER_CC_OUT")
    public JAXBElement<SYMFTTRANSFERCCOUTType> createSYMFTTRANSFERCCOUT(SYMFTTRANSFERCCOUTType value) {
        return new JAXBElement<SYMFTTRANSFERCCOUTType>(_SYMFTTRANSFERCCOUT_QNAME, SYMFTTRANSFERCCOUTType.class, null, value);
    }

}
