//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.27 at 07:04:38 PM GST 
//


package generated;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FT_FH_CREDIT_ACCT_COLL_OUTType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FT_FH_CREDIT_ACCT_COLL_OUTType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FT_FH_CREDIT_ACCT_T_OUT" type="{}FT_FH_CREDIT_ACCT_T_OUTType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FT_FH_CREDIT_ACCT_COLL_OUTType", propOrder = {
    "ftfhcreditaccttout"
})
public class FTFHCREDITACCTCOLLOUTType {

    @XmlElement(name = "FT_FH_CREDIT_ACCT_T_OUT")
    protected List<FTFHCREDITACCTTOUTType> ftfhcreditaccttout;

    /**
     * Gets the value of the ftfhcreditaccttout property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ftfhcreditaccttout property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFTFHCREDITACCTTOUT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FTFHCREDITACCTTOUTType }
     * 
     * 
     */
    public List<FTFHCREDITACCTTOUTType> getFTFHCREDITACCTTOUT() {
        if (ftfhcreditaccttout == null) {
            ftfhcreditaccttout = new ArrayList<FTFHCREDITACCTTOUTType>();
        }
        return this.ftfhcreditaccttout;
    }

}
