//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.27 at 07:04:38 PM GST 
//


package generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SA_ERRORSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SA_ERRORSType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ERRORS" type="{}SA_ERRLISTType" minOccurs="0"/>
 *         &lt;element name="BUGS" type="{}SA_BUGLISTType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SA_ERRORSType", propOrder = {
    "errors",
    "bugs"
})
public class SAERRORSType {

    @XmlElement(name = "ERRORS")
    protected SAERRLISTType errors;
    @XmlElement(name = "BUGS")
    protected SABUGLISTType bugs;

    /**
     * Gets the value of the errors property.
     * 
     * @return
     *     possible object is
     *     {@link SAERRLISTType }
     *     
     */
    public SAERRLISTType getERRORS() {
        return errors;
    }

    /**
     * Sets the value of the errors property.
     * 
     * @param value
     *     allowed object is
     *     {@link SAERRLISTType }
     *     
     */
    public void setERRORS(SAERRLISTType value) {
        this.errors = value;
    }

    /**
     * Gets the value of the bugs property.
     * 
     * @return
     *     possible object is
     *     {@link SABUGLISTType }
     *     
     */
    public SABUGLISTType getBUGS() {
        return bugs;
    }

    /**
     * Sets the value of the bugs property.
     * 
     * @param value
     *     allowed object is
     *     {@link SABUGLISTType }
     *     
     */
    public void setBUGS(SABUGLISTType value) {
        this.bugs = value;
    }

}
