//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.27 at 07:04:38 PM GST 
//


package generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SYM_STD_OUTType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SYM_STD_OUTType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HEADER_OUT" type="{}SA_HEADER_OUTType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SYM_STD_OUTType", propOrder = {
    "headerout"
})
public class SYMSTDOUTType {

    @XmlElement(name = "HEADER_OUT")
    protected SAHEADEROUTType headerout;

    /**
     * Gets the value of the headerout property.
     * 
     * @return
     *     possible object is
     *     {@link SAHEADEROUTType }
     *     
     */
    public SAHEADEROUTType getHEADEROUT() {
        return headerout;
    }

    /**
     * Sets the value of the headerout property.
     * 
     * @param value
     *     allowed object is
     *     {@link SAHEADEROUTType }
     *     
     */
    public void setHEADEROUT(SAHEADEROUTType value) {
        this.headerout = value;
    }

}
